services:
  app:
    image: securesignin-app:local
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SQLITE_DB_PATH=/app/data/securesignin.db
    volumes:
      - encryption_keys:/app/keys
      - ~/.SecureSignIn/data:/app/data
      - ./templates:/app/templates
      - ./static:/app/static
    networks:
      app-network:
        aliases:
          - app-service
    dns:
      - 8.8.8.8
      - 8.8.4.4
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

volumes:
  encryption_keys:

networks:
  app-network:
    driver: bridge
